### ISSUE TITLE
Invoke Athenian API as part of the deployed labeler

### ISSUE THREAD

**Issue by mads-hartmann** [gitpod-io/gitbot#68]
It turns out that Athenian can't use the deployed label to figure out the end-to-end cycle time of commits. To do that we need to invoke one of their APIs to mark the commit as deployed.

See their official docs [here](http://help.athenian.co/en/articles/5235189-refine-release-metrics-using-the-athenian-api)

```sh
curl -H "X-API-Key: <your-API-key> -d '[{"repository": "github.com/gitpod-io/gitpod", "commit": <commit-hash>}]'
```

So the rough steps are

1. Generate an API key (see link above) and put it into a secret and pass it to the deployed labeler
2. Update the deployed labeler so it invokes their API. Somewhere around [here](https://github.com/gitpod-io/gitbot/blob/83a287aaddddc3c6d03046940c4efc4db08f5c16/plugins/deployed-labeler/main.go#L177-L183) as that's where we add the "deployed" label which only gets added when all teams have deployed the change.

See [Slack thread](https://gitpod.slack.com/archives/C02NJDUUMC3/p1643816685705309)

**Comment by meysholdt** [comment]
hi @csweichel, can you give us a sense of the urgency of this issue? Would it work to move it to next week?

**Comment by meysholdt** [comment]
Duplicate: https://github.com/gitpod-io/ops/issues/3442

It came up in slack again here: https://gitpod.slack.com/archives/C01KGM9EBD4/p1658394881570459

And here: https://gitpod.slack.com/archives/C02NJDUUMC3/p1659534125231679

**Comment by meysholdt** [comment]
idea from platform sync: call Athenian form werft job directly instead of from deploy labeler.

**Comment by corneliusludmann** [comment]
Closing this since [we do not renew Athenian](https://gitpod.slack.com/archives/C01KGM9AW4W/p1667877534413109).
