### ISSUE TITLE
Require associated issues?

### ISSUE THREAD

**Issue by leodido** [gitpod-io/gitbot#9]
During our internal sync @svenefftinge brought up considerations whether we may want or want not to require issues associated with PRs.

In case we want (for all repos or for a subset of them) this we can do it with the `issue_required` field of the `approve` plugin.

https://github.com/kubernetes/test-infra/blob/e465d4fd9d61446fd3c7557d73c9f237b0ad1cf9/prow/plugins/config.go#L295

**Comment by csweichel** [comment]
I like this one. Will raise a PR.
